name: mola_gemini_flutter_template
description: "A new Flutter project with Gemini."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.2.1+48

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.3.2
  provider: ^6.1.2
  freezed: ^2.4.6
  path_provider: ^2.1.3
  flutter_state_notifier:
  freezed_annotation: ^2.4.1

  #AppIcon
  flutter_launcher_icons: ^0.13.1

  #Splash
  flutter_native_splash: ^2.4.0

  #ローカルDB
  shared_preferences: ^2.2.2

  #Http通信
  chopper: ^6.1.4

  # logger
  simple_logger: ^1.8.0+1

  # 環境変数
  flutter_dotenv: ^5.1.0

  #lottie
  lottie: ^2.7.0

  #画像選択
  image_picker: ^1.0.7

  #Slider
  syncfusion_flutter_sliders: ^25.2.3

  url_launcher: ^6.2.6


  #　同期
  rxdart: ^0.28.0
  synchronized: ^3.1.0

  app_tracking_transparency: ^2.0.5

  package_info_plus: ^8.0.0
  version: ^3.0.2
  
  #画像圧縮
  flutter_image_compress: ^2.2.0
  
  #広告
  google_mobile_ads: ^5.1.0
  
  #画像をギャラリーに保存
  image_gallery_saver_plus: ^3.0.5

  
  #画像のクロップと回転
  image_cropper: ^8.0.1

  #日付フォーマット
  intl: ^0.18.1

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  chopper_generator: ^6.0.3

  # Serializer
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/lottie/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/sake_icon.jpg"

flutter_native_splash:
  image: "assets/images/sake_logo.png"
  color: "#1D3567"
  android_gravity: fill
